version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.8.10
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - checkout
      - run:
          name: commit files
          command: 
                   git add .
                   git commit -a
                 
                   


workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
