on:
  schedule:
  - cron: "*/60 * * * *"
  
version: 2.1

jobs:
  test-and-lint:

    docker:
      - image: cimg/python:3.8.10
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
          # - deploy:
      #     name: commit files
      #     command: git config credential.helper 'cache --timeout=120'
      #              git config --local user.email "mike@mikeowino.com"
      #              git config --local user.name "Circle"
      #              git add .
      #              git commit -m "update data"
      #              git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/mikeyhodl/workflow.git master
      # - run:
      #     name: Clone docs
      #     working_directory: ~/workdir
      #     command: |
      #       git clone --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/mikeyhodl/workflow.git

      # - deploy:
      #     name: Trigger docs deployment
      #     working_directory: ~/workdir/docs
      #     command: |
      #       git config credential.helper 'cache --timeout=120'
      #       git config user.email "mike@mikeowino.com"
      #       git config user.name "Circle"
      #       git commit --allow-empty -m "Trigger deployment"
      #       git push -q https://${GITHUB_TOKEN}@github.com/mikeyhodl/workflow.git master

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint
